jobs:
  dependency-submission:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout sources
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set Java version
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '21'
    - continue-on-error: true
      name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v3
name: Dependency Submission
on:
  repository_dispatch:
    types: trigger-ga___dependency-submission.yml
permissions:
  contents: write
