jobs:
  fail-by-label:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: contains(github.event.pull_request.labels.*.name, 'do not merge')
      name: Fail if PR is labeled as "do not merge"
      run: 'echo "This PR is labeled as do not merge!"

        exit 1

        '
name: Check labels
on:
  repository_dispatch:
    types: trigger-ga___do-not-merge.yml
